security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        jwt:
            entity:
                class: App\Entity\Company
                property: email
        staff:
            entity:
                class: App\Entity\Staff
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            provider: jwt
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            # this is very weird for me, ikd why I should keep json login configuration here
            anonymous: lazy
            provider: staff
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            json_login:
                provider: jwt
                check_path: /authentication_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: app_logout
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
#         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allows accessing the Swagger UI
#         - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    encoders:
        App\Entity\Company:
            algorithm: auto
        App\Entity\StaffUser:
            algorithm: auto
        App\Entity\Staff:
            algorithm: auto
