version: '3.7'

volumes:
    postgres-data:
        driver: local

services:
    web:
        working_dir: /var/task
        image: bref/fpm-dev-gateway
        ports:
        - 8000:80
        volumes:
        - .:/var/task
        depends_on:
        - php
        - database
        env_file:
          - .env
        environment:
            HANDLER: public/index.php
            DOCUMENT_ROOT: public
            
    php:
        working_dir: /var/task
        image: bref/php-74-fpm-dev
        volumes:
        - .:/var/task

    database:
        image: postgres:11
        restart: always
        ports:
        - 5432:5432
        volumes:
        - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: kdti
            POSTGRES_USER: kdti
            POSTGRES_PASSWORD: kdti
            POSTGRES_HOST: database
            POSTGRES_PORT: 5432
            PGDATA: /var/lib/postgresql/data/pgdata

    adminer:
        image: adminer
        ports:
            - 8080:8080

    blackfire:
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: server-id
            BLACKFIRE_SERVER_TOKEN: server-token

    composer:
        image: composer
        command: composer
        working_dir: /var/task
        volumes:
            - .:/var/task
