easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        JobOffer:
            class: App\Entity\JobOffer
            list:
                fields: ['id', 'title', 'company']
            form:
                fields:
                    - { type: 'group', label: 'Job Offer Details', icon: 'paperclip' }
                    - { property: 'slug', type_options: { 'disabled': true } }
                    - { property: 'title' }
                    - { property: 'description', type: text_editor }
                    - { property: 'seniorityLevel' }
                    - { property: 'minimumSalary' }
                    - { property: 'maximumSalary' }
                    - { property: 'allowRemote' }
                    - { property: 'publishedAt', type_options: { widget: 'single_text' } }
                    - { property: 'status' }
                    - { property: 'company' }
